version: "3.7"
services:
 nginx:
  container_name: nginx
  image: nginx
  ports:
  - target: 80
    published: 80
    protocol: tcp
  volumes:
  - type: bind
    source: ./nginx/nginx.conf
    target: /etc/nginx/nginx.conf
  depends_on:
  - flask-host
  - flask-number
  - flask-letter
  - flask-sequence
  - flask-prize


 flask-host:
  container_name: flask-host
  image: 127.0.0.1:5000/flask-host:v1.0
  build:
   context: ./flask_host/
   args:
   - MYSQL_DB_TEST=${MYSQL_DB_TEST}
   - SECRET_KEY=${SECRET_KEY}
   - MYSQL_DB=${MYSQL_DB}
   - MYSQL_HOST=${MYSQL_HOST}
   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
   - MYSQL_USER=${MYSQL_USER}


 flask-number:
  container_name: flask-number
  image: 127.0.0.1:5000/flask-number:v1.0
  build: ./flask_generator_number/


 flask-letter:
  container_name: flask-letter
  image: 127.0.0.1:5000/flask-letter:v1.0
  build: ./flask_generator_letter/


 flask-sequence:
  container_name: flask-sequence
  image: 127.0.0.1:5000/flask-sequence:v1.0
  build: ./flask_generator_sequence/

 flask-prize:
  container_name: flask-prize
  image: 127.0.0.1:5000/flask-prize:v1.0
  build: ./flask_generator_prize/
