version: "3.3"
services:
 nginx:
  container_name: nginx
  image: nginx
  ports:
  - target: 80
    published: 80
    protocol: tcp
  volumes:
  - type: bind
    source: ./nginx/nginx.conf
    target: /etc/nginx/nginx.conf
  depends_on:
  - flask-host
  - flask-number
  - flask-letter
  - flask-sequence
  - flask-prize


 flask-host:
  container_name: flask-host
  image: 172.31.47.162:5000/flask-host:build-${BUILD_NUMBER}
  build:
   context: ./flask_host/
   args:
   - MYSQL_DB_TEST=${MYSQL_DB_TEST}
   - SECRET_KEY=${SECRET_KEY}
   - MYSQL_DB=${MYSQL_DB}
   - MYSQL_HOST=${MYSQL_HOST}
   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
   - MYSQL_USER=${MYSQL_USER}


 flask-number:
  container_name: flask-number
  image: 172.31.47.162:5000/flask-number:build-${BUILD_NUMBER}
  build: ./flask_generator_number/


 flask-letter:
  container_name: flask-letter
  image: 172.31.47.162:5000/flask-letter:build-${BUILD_NUMBER}
  build: ./flask_generator_letter/


 flask-sequence:
  container_name: flask-sequence
  image: 172.31.47.162:5000/flask-sequence:build-${BUILD_NUMBER}
  build: ./flask_generator_sequence/

 flask-prize:
  container_name: flask-prize
  image: 172.31.47.162:5000/flask-prize:build-${BUILD_NUMBER}
  build: ./flask_generator_prize/
