version: "3.7"
services:
 flask-host:
  container_name: flask-host
  image: flask-host
  build: ./flask_host/
  ports:
  - target: 5000
    published: 5000
    protocol: tcp
  environment:
  - MYSQL_DB_TEST=${MYSQL_DB_TEST}
  - SECRET_KEY=${SECRET_KEY}
  - MYSQL_DB=${MYSQL_DB}
  - MYSQL_HOST=${MYSQL_HOST}
  - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  - MYSQL_USER=${MYSQL_USER}
  - IP=35.187.176.113
  depends_on:
  - flask-number
  - flask-letter
  - flask-sequence
  - flask-prize
 flask-number:
  container_name: flask-number
  image: flask-number
  build: ./flask_generator_number/
  ports:
  - target: 5000
    published: 5001
    protocol: tcp
  environment:
  - IP=35.187.176.113
 flask-letter:
  container_name: flask-letter
  image: flask-letter
  build: ./flask_generator_letter/
  ports:
  - target: 5000
    published: 5002
    protocol: tcp
  environment:
  - IP=35.187.176.113
 flask-sequence:
  container_name: flask-sequence
  image: flask-sequence
  build: ./flask_generator_sequence/
  ports:
  - target: 5000
    published: 5003
    protocol: tcp
  environment:
  - IP=35.187.176.113
 flask-prize:
  container_name: flask-prize
  image: flask-prize
  build: ./flask_generator_prize/
  ports:
  - target: 5000
    published: 5004
    protocol: tcp
  environment:
  - IP=35.187.176.113
